In [10]:
using Distributions, Statistics, StatsPlots, Plots, LinearAlgebra

In [43]:
S = [1,2, 3, 4, 5,]
E = [0.2, 0.2, 0.2, 0.2, 0.2]
A = [0. 0. 0. 0. 0.5; 0.5 0. 0.5 1. 0.; 0. 0. 0. 0. 0.; 0. 0.5 0.5 0. 0.5; 0.5 0.5 0 0 0]

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.5
 0.5  0.0  0.5  1.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.5  0.5  0.0  0.5
 0.5  0.5  0.0  0.0  0.0

In [44]:
function ite(S, A, E, tol=0.01)
    R = S
    
    δ = tol+1
    
    while δ > tol
        R_1 = A*R
        d = norm(R_1,1)-norm(R,1)
        R_1 = R_1 + d*E
        δ= norm(R_1-R, 1)
        R = R_1
        println(R)
    end
    return R
end

S1 = S*100
ite(S,A, E)

[2.5, 6.0, 0.0, 5.0, 1.5]
[0.75, 6.25, 0.0, 3.75, 4.25]
[2.125, 4.125, 0.0, 5.25, 3.5]
[1.75, 6.3125, 0.0, 3.8125, 3.125]
[1.5625, 4.6875, 0.0, 4.71875, 4.03125]
[2.015625, 5.5, 0.0, 4.359375, 3.125]
[1.5625, 5.3671875, 0.0, 4.3125, 3.7578125]
[1.87890625, 5.09375, 0.0, 4.5625, 3.46484375]
[1.732421875, 5.501953125, 0.0, 4.279296875, 3.486328125]
[1.7431640625, 5.1455078125, 0.0, 4.494140625, 3.6171875]
[1.80859375, 5.36572265625, 0.0, 4.38134765625, 3.4443359375]
[1.72216796875, 5.28564453125, 0.0, 4.405029296875, 3.587158203125]
[1.7935791015625, 5.26611328125, 0.0, 4.4364013671875, 3.50390625]
[1.751953125, 5.33319091796875, 0.0, 4.385009765625, 3.52984619140625]
[1.764923095703125, 5.260986328125, 0.0, 4.4315185546875, 3.542572021484375]
[1.7712860107421875, 5.3139801025390625, 0.0, 4.4017791748046875, 3.5129547119140625]
[1.7564773559570312, 5.287422180175781, 0.0, 4.4134674072265625, 3.542633056640625]
[1.7713165283203125, 5.291706085205078, 0.0, 4.415027618408203, 3.521949768066

5-element Array{Float64,1}:
 1.7637620568275452
 5.295037090778351 
 0.0               
 4.410956978797913 
 3.5302438735961914

In [46]:
E1 = [0., 0., 0., 100000000, 0.]
ite(S,A,E1,0.01)

[2.5, 6.0, 0.0, 5.0, 1.5]
[0.75, 6.25, 0.0, 3.75, 4.25]
[2.125, 4.125, 0.0, 5.25, 3.5]
[1.75, 6.3125, 0.0, 3.8125, 3.125]
[1.5625, 4.6875, 0.0, 4.71875, 4.03125]
[2.015625, 5.5, 0.0, 4.359375, 3.125]
[1.5625, 5.3671875, 0.0, 4.3125, 3.7578125]
[1.87890625, 5.09375, 0.0, 4.5625, 3.46484375]
[1.732421875, 5.501953125, 0.0, 4.279296875, 3.486328125]
[1.7431640625, 5.1455078125, 0.0, 4.494140625, 3.6171875]
[1.80859375, 5.36572265625, 0.0, 4.38134765625, 3.4443359375]
[1.72216796875, 5.28564453125, 0.0, 4.405029296875, 3.587158203125]
[1.7935791015625, 5.26611328125, 0.0, 4.4364013671875, 3.50390625]
[1.751953125, 5.33319091796875, 0.0, 4.385009765625, 3.52984619140625]
[1.764923095703125, 5.260986328125, 0.0, 4.4315185546875, 3.542572021484375]
[1.7712860107421875, 5.3139801025390625, 0.0, 4.4017791748046875, 3.5129547119140625]
[1.7564773559570312, 5.287422180175781, 0.0, 4.4134674072265625, 3.542633056640625]
[1.7713165283203125, 5.291706085205078, 0.0, 4.415027618408203, 3.521949768066

5-element Array{Float64,1}:
 1.7637620568275452
 5.295037090778351 
 0.0               
 4.410956978797913 
 3.5302438735961914

In [12]:
abs(1)

1

In [66]:
W = [0 0.5 0.33 0; 0 0 0.33 1; 1 0 0 0; 0 0.5 0.33 0]

4×4 Array{Float64,2}:
 0.0  0.5  0.33  0.0
 0.0  0.0  0.33  1.0
 1.0  0.0  0.0   0.0
 0.0  0.5  0.33  0.0

In [67]:
e0 = [1,0,0,0]

4-element Array{Int64,1}:
 1
 0
 0
 0

In [68]:
r_i=W*e0

4-element Array{Float64,1}:
 0.0
 0.0
 1.0
 0.0

In [87]:
r_i= W*r_i

4-element Array{Float64,1}:
 0.21861430031479906
 0.2941996817854518 
 0.2219737814184558 
 0.21861430031479906

In [90]:
c = 0.9

rwri = c*W*e0 + (1-c)*e0

4-element Array{Float64,1}:
 0.09999999999999998
 0.0                
 0.9                
 0.0                

In [104]:
rwri = c*W*rwri + (1-c)*e0

4-element Array{Float64,1}:
 0.2871634710906594 
 0.2465652873209464 
 0.25991389174796015
 0.1871634710906594 

In [ ]:
###The system matrix = I-cW

In [116]:
Q = I(4)-c*W

Q_i = inv(Q)

r_system = (1-c)*Q_i*e0

4-element Array{Float64,1}:
 0.2868644987103152 
 0.24485692934455094
 0.25817804883928364
 0.18686449871031516

In [130]:
W_0 = [0 100 150 0; 0 0 150 40; 200 0 0 0; 0 100 150 0]

D = Diagonal([250, 190, 200, 250])

D_1_2 = D^(-1/2)

W_0

4×4 Array{Int64,2}:
   0  100  150   0
   0    0  150  40
 200    0    0   0
   0  100  150   0

In [129]:
L = D_1_2*W_0*D_1_2

4×4 Array{Float64,2}:
 0.0       0.458831  0.67082   0.0     
 0.0       0.0       0.769484  0.183533
 0.894427  0.0       0.0       0.0     
 0.0       0.458831  0.67082   0.0     

In [181]:
a = [0 2 3; 2 0 6; 3 6 0]
ei = eigen(a)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
3-element Array{Float64,1}:
 -6.098706201013971 
 -1.5445925897776727
  7.643298790791668 
eigenvectors:
3×3 Array{Float64,2}:
 -0.138138   0.896297  -0.421391
 -0.671202  -0.397585  -0.625631
  0.72829   -0.196414  -0.656518

In [182]:
e_val = ei.values
e_vec = ei.vectors

3×3 Array{Float64,2}:
 -0.138138   0.896297  -0.421391
 -0.671202  -0.397585  -0.625631
  0.72829   -0.196414  -0.656518

In [183]:
e_vec*Diagonal(e_val)

3×3 Array{Float64,2}:
  0.842466  -1.38441   -3.22082
  4.09346    0.614107  -4.78189
 -4.44163    0.30338   -5.01796

In [184]:
e_vec*Diagonal(e_val)*e_vec'

3×3 Array{Float64,2}:
 4.66294e-15  2.0          3.0        
 2.0          6.66134e-15  6.0        
 3.0          6.0          1.28786e-14

In [185]:
e_val[1]*e_vec[:,1]

3-element Array{Float64,1}:
  0.8424660620245374
  4.09346189810942  
 -4.441625597610582 

In [186]:
a*e_vec[:,1]

3-element Array{Float64,1}:
  0.8424660620245434
  4.093461898109433 
 -4.441625597610598 

In [187]:
c = 0.9
inv(inv(Diagonal(e_val))-c*e_vec'*e_vec)

3×3 Array{Float64,2}:
 -0.939877      8.42913e-17   0.0    
  8.42913e-17  -0.646237     -0.0    
 -6.78314e-17   1.16598e-17  -1.30011

In [191]:
x = zeros(3,3)
for i=1:3
     x+=(e_val[i]/(1-c*e_val[i]))*e_vec[:,i]*e_vec[:,i]'
end

e_val[1]/(1-c*e_val[1]),e_val[2]/(1-c*e_val[2])

(-0.9398768276628553, -0.6462369985279207)

In [166]:
e_vec[:,1]*e_vec[:,1]'

3×3 Array{Float64,2}:
  0.00995287   0.0788403  -0.060316
  0.0788403    0.624522   -0.477785
 -0.060316    -0.477785    0.365525

In [175]:
inv(inv(Diagonal(e_val))-c*I(3))

3×3 Diagonal{Float64,Array{Float64,1}}:
 1.63927    ⋅         ⋅     
  ⋅       -2.71678    ⋅     
  ⋅         ⋅       -1.20361

In [169]:
1/e_val[1]

1.510026885778542

In [171]:
e_vec*e_vec'

3×3 Array{Float64,2}:
  1.0          -2.77556e-17  2.77556e-17
 -2.77556e-17   1.0          5.55112e-17
  2.77556e-17   5.55112e-17  1.0        

In [172]:
e_vec'*e_vec

3×3 Array{Float64,2}:
 1.0          4.16334e-17  5.55112e-17
 4.16334e-17  1.0          0.0        
 5.55112e-17  0.0          1.0        

In [204]:
## USU'

U = [4 3; 3 4]
S = [1 0; 0 8]



2×2 Array{Int64,2}:
 1  0
 0  8

In [205]:
a = eigen(U)
U = a.vectors

2×2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107

In [206]:
U * U'*S

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  8.0

In [207]:
U * S * U'

2×2 Array{Float64,2}:
 4.5  3.5
 3.5  4.5

In [209]:
x = 1 * U[:,1] * U[1,:]'

2×2 Array{Float64,2}:
  0.5  -0.5
 -0.5   0.5

In [210]:
y = 8 * U[:,2] * U[2,:]'

2×2 Array{Float64,2}:
 4.0  4.0
 4.0  4.0